const state={file:null,metadata:null,detection:null,verified:false,selected:{}};const $=id=>document.getElementById(id);const setStatus=t=>$('status').textContent=t;
function render(m){state.metadata=m;$('review').classList.remove('hidden');$('title').value=m.title||'';$('description').value=m.description||'';renderKeywords(m.keywords||[]);const q=m.quality||{};$('score').textContent=`Quality ${q.score??'—'}/100`;const ws=q.warnings||[];$('warnings').innerHTML=ws.length?`<b>Review warnings</b><ul>${ws.map(x=>`<li>${x}</li>`).join('')}</ul>`:'';$('warnings').classList.toggle('hidden',!ws.length);}
function renderKeywords(list){$('keywords').innerHTML='';list.forEach((k,i)=>{const s=document.createElement('span');s.className='kw';s.textContent=k;const b=document.createElement('button');b.textContent='×';b.onclick=()=>{state.metadata.keywords.splice(i,1);renderKeywords(state.metadata.keywords)};s.appendChild(b);$('keywords').appendChild(s)});$('keywordCount').textContent=`(${list.length}/50)`;}
async function tab(){return(await chrome.tabs.query({active:true,currentWindow:true}))[0]}
function renderDetection(r){state.detection=r;state.verified=false;$('scanStatus').textContent=`${r.detected}/${r.total} fields detected`;$('detection').innerHTML=Object.entries(r.best).map(([k,f])=>`<div class="detectRow"><span>${f?'✓':'✕'}</span><b>${k}</b><small>${f?`${f.tag} · score ${f.score}`:'Not detected'}</small></div>`).join('');$('detection').classList.remove('hidden');$('verifyBtn').disabled=!r.ready;$('fillBtn').disabled=true;$('verification').classList.add('hidden');}
async function scanPage(){try{const t=await tab();const r=await chrome.tabs.sendMessage(t.id,{type:'STOCKPILOT_SCAN'});renderDetection(r)}catch(e){$('scanStatus').textContent='Cannot scan. Open Adobe Stock Contributor.';$('verifyBtn').disabled=true;$('fillBtn').disabled=true;}}
async function verify(){const t=await tab();const r=await chrome.tabs.sendMessage(t.id,{type:'STOCKPILOT_VERIFY_FILL',selected:{title:true,description:true,keywords:true,category:true}});state.verified=r.verified;state.selected={title:true,description:true,keywords:true,category:true};$('verification').classList.remove('hidden');$('verification').textContent=r.verified?'✓ All 4 fields verified. Ready to fill.':'⚠ Verification failed. Review detection.';$('fillBtn').disabled=!r.verified;}
async function fill(){if(!state.verified||!state.metadata)return;const t=await tab();const r=await chrome.tabs.sendMessage(t.id,{type:'STOCKPILOT_FILL',metadata:state.metadata,selected:state.selected});setStatus(`Filled ${Object.values(r.filled).filter(Boolean).length}/4 fields. Review before submitting.`);}
$('settingsBtn').onclick=()=>chrome.runtime.openOptionsPage();$('scanBtn').onclick=scanPage;$('verifyBtn').onclick=verify;$('fillBtn').onclick=fill;$('imageInput').onchange=e=>{state.file=e.target.files[0];$('analyzeBtn').disabled=!state.file;setStatus(state.file?state.file.name:'')};$('analyzeBtn').onclick=analyze;$('regenerateBtn').onclick=analyze;
async function analyze(){if(!state.file)return;setStatus('Analyzing image…');$('analyzeBtn').disabled=true;try{const c=await chrome.storage.local.get(['backendUrl']);const fd=new FormData();fd.append('image',state.file);const r=await fetch((c.backendUrl||'http://127.0.0.1:8787')+'/analyze',{method:'POST',body:fd});if(!r.ok)throw new Error(await r.text());render(await r.json());setStatus('Analysis complete. Review before filling.')}catch(e){setStatus(`Error: ${e.message}`)}finally{$('analyzeBtn').disabled=false}}
$('title').oninput=e=>state.metadata&&(state.metadata.title=e.target.value);$('description').oninput=e=>state.metadata&&(state.metadata.description=e.target.value);