const state={file:null,metadata:null,detection:null};
const $=id=>document.getElementById(id);
const escapeHtml=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const setStatus=t=>{$('status').textContent=t};
function render(m){state.metadata=m;$('review').classList.remove('hidden');$('title').value=m.title||'';$('description').value=m.description||'';renderKeywords(m.keywords||[]);const q=m.quality||{};$('score').textContent=`Quality ${q.score??'—'}/100`;const ws=q.warnings||[];$('warnings').innerHTML=ws.length?`<b>Review warnings</b><ul>${ws.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul>`:'';$('warnings').classList.toggle('hidden',!ws.length);$('fillBtn').disabled=!state.metadata||!state.detection?.ready;$('reviewFillBtn').disabled=!state.metadata;}
function renderKeywords(list){$('keywords').innerHTML='';list.forEach((k,i)=>{const s=document.createElement('span');s.className='kw';s.textContent=k;const b=document.createElement('button');b.textContent='×';b.onclick=()=>{state.metadata.keywords.splice(i,1);renderKeywords(state.metadata.keywords)};s.appendChild(b);$('keywords').appendChild(s)});$('keywordCount').textContent=`(${list.length}/50)`;}
async function tab(){return (await chrome.tabs.query({active:true,currentWindow:true}))[0];}
async function scanPage(){ $('scanStatus').textContent='Scanning page…';$('detection').classList.add('hidden');try{const t=await tab();const r=await chrome.tabs.sendMessage(t.id,{type:'STOCKPILOT_SCAN'});state.detection=r;renderDetection(r);}catch(e){$('scanStatus').textContent='Cannot scan. Open Adobe Stock Contributor.';$('fillBtn').disabled=true;}}
function renderDetection(r){const labels={title:'Title',description:'Description',keywords:'Keywords',category:'Category'};$('scanStatus').textContent=`${r.detected}/${r.total} fields detected`;$('detection').innerHTML=Object.entries(labels).map(([k,l])=>{const f=r.fields[k];return `<div class="detectRow"><span>${f.found?'✓':'✕'}</span><b>${l}</b><small>${f.found?`${f.tag} · score ${f.score}`:'Not detected'}</small></div>`}).join('');$('detection').classList.remove('hidden');$('fillBtn').disabled=!state.metadata||!r.ready;}
async function fillAdobe(){if(!state.metadata)return;try{const t=await tab();const r=await chrome.tabs.sendMessage(t.id,{type:'STOCKPILOT_FILL',metadata:state.metadata});setStatus(`Filled ${Object.values(r.detected).filter(Boolean).length}/4 fields. Review before submitting.`);await scanPage();}catch(e){setStatus('Open an Adobe Stock Contributor page first.');}}
$('settingsBtn').onclick=()=>chrome.runtime.openOptionsPage();$('scanBtn').onclick=scanPage;$('fillBtn').onclick=fillAdobe;$('reviewFillBtn').onclick=fillAdobe;
$('imageInput').onchange=e=>{state.file=e.target.files[0];$('analyzeBtn').disabled=!state.file;setStatus(state.file?state.file.name:'');};
$('analyzeBtn').onclick=analyze;$('regenerateBtn').onclick=analyze;
async function analyze(){if(!state.file)return;setStatus('Analyzing image…');$('analyzeBtn').disabled=true;try{const c=await chrome.storage.local.get(['backendUrl']);const fd=new FormData();fd.append('image',state.file);const r=await fetch((c.backendUrl||'http://127.0.0.1:8787')+'/analyze',{method:'POST',body:fd});if(!r.ok)throw new Error(await r.text());render(await r.json());setStatus('Analysis complete. Review before filling.');}catch(e){setStatus(`Error: ${e.message}`)}finally{$('analyzeBtn').disabled=false;}}
$('title').oninput=e=>state.metadata&&(state.metadata.title=e.target.value);$('description').oninput=e=>state.metadata&&(state.metadata.description=e.target.value);