const state={id:null,file:null,metadata:null,detection:null,verified:false,selected:{}};const $=id=>document.getElementById(id);const setStatus=t=>$('status').textContent=t;
function render(m){state.metadata=m;$('review').classList.remove('hidden');$('title').value=m.title||'';$('description').value=m.description||'';renderKeywords(m.keywords||[]);const q=m.quality||{};$('score').textContent=`Quality ${q.score??'—'}/100`;const ws=q.warnings||[];$('warnings').innerHTML=ws.length?`<b>Review warnings</b><ul>${ws.map(x=>`<li>${x}</li>`).join('')}</ul>`:'';$('warnings').classList.toggle('hidden',!ws.length);}
function renderKeywords(list){$('keywords').innerHTML='';list.forEach((k,i)=>{const s=document.createElement('span');s.className='kw';s.textContent=k;const b=document.createElement('button');b.textContent='×';b.onclick=()=>{state.metadata.keywords.splice(i,1);renderKeywords(state.metadata.keywords);saveEditsDebounced()};s.appendChild(b);$('keywords').appendChild(s)});$('keywordCount').textContent=`(${list.length}/50)`;}
async function tab(){return(await chrome.tabs.query({active:true,currentWindow:true}))[0]}
function renderDetection(r){state.detection=r;state.verified=false;$('scanStatus').textContent=`${r.detected}/${r.total} fields detected`;$('detection').innerHTML=Object.entries(r.best).map(([k,f])=>`<div class="detectRow"><span>${f?'✓':'✕'}</span><b>${k}</b><small>${f?`${f.tag} · score ${f.score}`:'Not detected'}</small></div>`).join('');$('detection').classList.remove('hidden');$('verifyBtn').disabled=!r.ready;$('fillBtn').disabled=true;$('verification').classList.add('hidden');}
async function scanPage(){try{const t=await tab();const r=await chrome.tabs.sendMessage(t.id,{type:'STOCKPILOT_SCAN'});renderDetection(r)}catch(e){$('scanStatus').textContent='Cannot scan. Open Adobe Stock Contributor.';$('verifyBtn').disabled=true;$('fillBtn').disabled=true;}}
const backendUrl=async()=>((await chrome.storage.local.get({backend:'http://127.0.0.1:8787'})).backend).replace(/\/$/,'');
async function saveEdits(filled){if(!state.id||!state.metadata)return;try{const m=state.metadata;await fetch(`${await backendUrl()}/history/${state.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:m.title,description:m.description,keywords:m.keywords,category:m.category,filled})})}catch{}}
async function loadHistory(){const sel=$('history');try{const r=await fetch(`${await backendUrl()}/history?limit=20`);const d=await r.json();sel.innerHTML='<option value="">History…</option>'+d.items.map(i=>`<option value="${i.id}">${(i.title||i.fileName||'#'+i.id).replace(/</g,'&lt;').slice(0,40)}${i.filledAt?' ✓':''}</option>`).join('')}catch{}}
async function openHistory(){const id=$('history').value;if(!id)return;try{const r=await fetch(`${await backendUrl()}/history/${id}`);const d=await r.json();if(!r.ok)throw new Error(d.error);state.id=d.item.id;state.verified=false;$('fillBtn').disabled=true;render({title:d.item.title,description:d.item.description,keywords:d.item.keywords,category:d.item.category,quality:{score:d.item.score,warnings:d.item.warnings}});setStatus('Loaded from history.')}catch(e){setStatus(`Error: ${e.message}`)}}
let editTimer;const saveEditsDebounced=()=>{clearTimeout(editTimer);editTimer=setTimeout(()=>saveEdits(false),600)};
const FIELDS=['title','description','keywords','category'];
const allSelected=()=>Object.fromEntries(FIELDS.map(f=>[f,true]));
async function verify(){try{const t=await tab();const r=await chrome.tabs.sendMessage(t.id,{type:'STOCKPILOT_VERIFY_FILL',metadata:state.metadata||{},selected:allSelected()});
 state.verified=r.verified;state.selected=allSelected();const bad=Object.entries(r.fields).filter(([,f])=>!f.ok).map(([k,f])=>`${k} (${f.reason})`);
 $('verification').classList.remove('hidden');$('verification').textContent=r.verified?'✓ All 4 fields located with confidence. Ready to fill.':`⚠ Cannot fill safely: ${bad.join(', ')}`;
 $('fillBtn').disabled=!(r.verified&&state.metadata)}catch(e){$('verification').classList.remove('hidden');$('verification').textContent='⚠ Cannot reach the page. Reload Adobe Stock.';$('fillBtn').disabled=true}}
async function fill(){if(!state.verified||!state.metadata)return;try{const t=await tab();const r=await chrome.tabs.sendMessage(t.id,{type:'STOCKPILOT_FILL',metadata:state.metadata,selected:state.selected});
 const n=Object.values(r.filled).filter(x=>x.verified).length;const bad=Object.entries(r.filled).filter(([,x])=>!x.verified).map(([k])=>k);
 setStatus(`Filled & confirmed ${n}/${Object.keys(r.filled).length} fields.${bad.length?' Check manually: '+bad.join(', ')+'.':''} Review before submitting.`);saveEdits(true)}catch(e){setStatus(`Error: ${e.message}`)}}
$('history').onchange=openHistory;loadHistory();$('settingsBtn').onclick=()=>chrome.runtime.openOptionsPage();$('scanBtn').onclick=scanPage;$('verifyBtn').onclick=verify;$('fillBtn').onclick=fill;$('imageInput').onchange=e=>{state.file=e.target.files[0];$('analyzeBtn').disabled=!state.file;setStatus(state.file?state.file.name:'')};$('analyzeBtn').onclick=analyze;$('regenerateBtn').onclick=analyze;
const toBase64=f=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=()=>rej(r.error);r.readAsDataURL(f)});
async function analyze(){if(!state.file)return;setStatus('Analyzing image…');$('analyzeBtn').disabled=true;$('regenerateBtn').disabled=true;
 try{const c=await chrome.storage.local.get({provider:'gemini',apiKey:'',model:'',backend:'http://127.0.0.1:8787'});
  const body={provider:c.provider,apiKey:c.apiKey||undefined,model:c.model||undefined,mimeType:state.file.type,fileName:state.file.name,imageBase64:await toBase64(state.file)};
  const r=await fetch(c.backend.replace(/\/$/,'')+'/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
  const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);
  state.id=data.id;render(data.metadata);loadHistory();state.verified=false;$('fillBtn').disabled=true;setStatus('Analysis complete. Review, then Verify before filling.')}
 catch(e){setStatus(`Error: ${e.message}`)}finally{$('analyzeBtn').disabled=false;$('regenerateBtn').disabled=false}}
$('title').oninput=e=>{if(state.metadata){state.metadata.title=e.target.value;saveEditsDebounced();state.verified=false;$('fillBtn').disabled=true}};$('description').oninput=e=>{if(state.metadata){state.metadata.description=e.target.value;saveEditsDebounced()}};